apiKey: null
buildOnly: false
cluster: null
clusterId: null
command: bash scripts/run.sh --target-iteration 250000
container: ufoym/deepo:all-py36-cu100
envVars: null
experimentId: null
ignoreFiles: null
isPreemptible: null
isPublic: null
machineType: P6000
name: dfl-training
nodeAttrs: null
ports: null
project: null
projectId: pr6b7rwbn
registryPassword: null
registryTarget: null
registryTargetPassword: null
registryTargetUsername: null
registryUsername: null
relDockerfilePath: null
startedByUserId: null
tag: null
tags: null
useDockerfile: null
workingDirectory: null
workspace: ./
